name-template: 'Draft (next release)'
tag-template: 'v$NEXT_PATCH_VERSION'
sort-direction: descending
categories:
  - title: '🚨 Breaking changes'
    labels:
      - 'breaking change'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'housekeeping'
      - 'refactor'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  $CHANGES
  $CONTRIBUTORS
